services:
  db:
    image: mysql:8.0
    container_name: mysql_lmsgi_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456@23
      MYSQL_DATABASE: gestion_informacion
      MYSQL_USER: alumno_dam_daw
      MYSQL_PASSWORD: 123456@23
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: